APP_ENV_DEFAULT = "development"
APP_VERSION_DEFAULT = "0.1.0"

LOG_LEVEL_DEFAULT = "INFO"
LOG_FORMAT_DEFAULT = "json"

API_HOST_DEFAULT = "0.0.0.0"
API_PORT_DEFAULT = 8000

DATA_LAKE_PATH_DEFAULT = "./data/lake"
BRONZE_PATH_DEFAULT = "bronze"
SILVER_PATH_DEFAULT = "silver"
GOLD_PATH_DEFAULT = "gold"
QUARANTINE_PATH_DEFAULT = "quarantine"

PRIMARY_SOURCE_NAME_DEFAULT = "PrimarySource"
PRIMARY_SOURCE_TYPE_DEFAULT = "REST"
PRIMARY_SOURCE_URL_DEFAULT = ""
PRIMARY_SOURCE_API_KEY_DEFAULT = ""

SECOND_SOURCE_NAME_DEFAULT = "SecondSource"
SECOND_SOURCE_TYPE_DEFAULT = "REST"
SECOND_SOURCE_URL_DEFAULT = ""
SECOND_SOURCE_API_KEY_DEFAULT = ""

REQUEST_TIMEOUT_DEFAULT = 30
MAX_RETRIES_DEFAULT = 3
VERIFY_SSL_DEFAULT = True

CIRCUIT_BREAKER_FAILURE_THRESHOLD_DEFAULT = 5
CIRCUIT_BREAKER_SUCCESS_THRESHOLD_DEFAULT = 2
CIRCUIT_BREAKER_RECOVERY_TIMEOUT_DEFAULT = 30
CIRCUIT_BREAKER_HALF_OPEN_MAX_CALLS_DEFAULT = 1
TRUST_SCORE_THRESHOLD_DEFAULT = 0.80
ALLOW_SOURCE_FAILOVER_DEFAULT = True

DAGSTER_POSTGRES_HOST_DEFAULT = "dagster_postgres"
DAGSTER_POSTGRES_PORT_DEFAULT = 5432
DAGSTER_POSTGRES_USER_DEFAULT = "dagster"
DAGSTER_POSTGRES_PASSWORD_DEFAULT = ""
DAGSTER_POSTGRES_DB_DEFAULT = "dagster"
DAGSTER_POSTGRES_EXPORT_PORT_DEFAULT = 5432
DAGSTER_WEBSERVER_PORT_DEFAULT = 3000
DAGSTER_HOME_DEFAULT = "/opt/dagster"

OPENAI_API_KEY_DEFAULT = ""

SECRET_KEY_DEFAULT = ""
