APP_ENV_DEFAULT = "development"
APP_VERSION_DEFAULT = "0.1.0"

LOG_LEVEL_DEFAULT = "INFO"
LOG_FORMAT_DEFAULT = "json"

API_HOST_DEFAULT = "0.0.0.0"
API_PORT_DEFAULT = 8000

DATA_LAKE_PATH_DEFAULT = "./data/lake"
BRONZE_PATH_DEFAULT = "bronze"
SILVER_PATH_DEFAULT = "silver"
GOLD_PATH_DEFAULT = "gold"
QUARANTINE_PATH_DEFAULT = "quarantine"
